/* 
 This file was generated by Dashcode.  
 You may edit this file to customize your widget or web page 
 according to the license.txt file included in the project.
 */

//
// Function: load()
// Called by HTML body element's onload event when the web application is ready to start
//
function load()
{
    dashcode.setupParts();
}


function rowClicked(event)
{
    // get the title of the selected movie
    var listController = dashcode.getDataSource("trailersList");
    var title = listController.valueForKeyPath("selection.info.title");
    
    // a trailer row was clicked, go to the detail view
    var browserObject = document.getElementById("browser").object;
    browserObject.goForward("detailView", title);
    
    // the rest of the data will be filled in with bindings...
}


function playTrailer(event)
{
    // go to the trailer's video URL
    var listController = dashcode.getDataSource("trailersList");
    var trailerURL = listController.valueForKeyPath("selection.preview.large");
    window.location = trailerURL;
}
