/* 
 This file was generated by Dashcode and is covered by the 
 license.txt included in the project.  You may edit this file, 
 however it is recommended to first turn off the Dashcode 
 code generator otherwise the changes will be lost.
 */
var dashcodePartSpecs = {
    "detailBox": { "propertyValues": { "visibleBinding": { "keypath": "trailersList.hasSelection" } }, "view": "DC.View" },
    "detailDescription": { "propertyValues": { "textBinding": { "keypath": "trailersList.selection.info.description" } }, "text": "Description", "view": "DC.Text" },
    "detailDirector": { "propertyValues": { "textBinding": { "keypath": "trailersList.selection.info.director" } }, "text": "Director", "view": "DC.Text" },
    "detailPoster": { "propertyValues": { "srcBinding": { "keypath": "trailersList.selection.poster.xlarge", "multipleValuesPlaceholder": "../Images/MoviePlaceholder.png", "noSelectionPlaceholder": "../Images/MoviePlaceholder.png", "nullValuePlaceholder": "../Images/MoviePlaceholder.png" } }, "view": "DC.ImageLayout" },
    "detailTitle": { "propertyValues": { "textBinding": { "keypath": "trailersList.selection.info.title" } }, "text": "Title", "view": "DC.Text" },
    "playButton": { "customImage": "../Images/play.png", "customImagePosition": "DC.PushButton.IMAGE_POSITION_LEFT", "customImagePressed": "../Images/play_pressed.png", "initialHeight": 34, "initialWidth": 125, "leftImageWidth": 5, "onclick": "toggleStackLayout", "rightImageWidth": 5, "text": "Play Trailer", "view": "DC.PushButton" },
    "rating": { "propertyValues": { "srcBinding": { "keypath": "trailersList.selection.info.rating", "transformer": "ratingToImage" } }, "view": "DC.ImageLayout" },
    "rowPoster": { "propertyValues": { "srcBinding": { "keypath": "*.poster.location", "multipleValuesPlaceholder": "../Images/MoviePlaceholder.png", "noSelectionPlaceholder": "../Images/MoviePlaceholder.png", "nullValuePlaceholder": "../Images/MoviePlaceholder.png" } }, "view": "DC.ImageLayout" },
    "rowTitle": { "propertyValues": { "textBinding": { "keypath": "*.info.title" } }, "text": "Movie Title", "view": "DC.Text" },
    "search": { "propertyValues": { "predicate": "info.title", "predicateBinding": { "keypath": "trailersList.filterPredicate" } }, "view": "DC.SearchField" },
    "splitLayout": { "flexibleViewIndex": 1, "initialSize": 768, "initialSplitterSize": 1, "isVertical": true, "splitterPosition": 303, "view": "DC.SplitLayout" },
    "stackLayout": { "subviewsTransitions": [{ "direction": "top-bottom", "duration": "2", "timing": "ease-in-out", "type": "push" }, { "direction": "bottom-top", "duration": "2", "timing": "ease-in-out", "type": "push" }], "view": "DC.StackLayout" },
    "text": { "text": "Back", "view": "DC.Text" },
    "trailersList": { "allowsEmptySelection": true, "allowsMultipleSelection": true, "dataArray": ["Item 1", "Item 2", "Item 3"], "labelElementId": "rowTitle", "listStyle": "List.DESKTOP_LIST", "propertyValues": { "dataArrayBinding": { "keypath": "dataSource.content.movieinfo" } }, "sampleRows": 3, "selectionEnabled": true, "useDataSource": true, "view": "DC.List" },
    "video": { "propertyValues": { "srcBinding": { "keypath": "trailersList.selection.preview.large" } }, "view": "DC.VideoLayout" }
};



